services:
  - type: web
    name: puppeteer-3ds-api
    env: node
    region: ohio
    plan: free
    buildCommand: |
      npm install
      npx puppeteer browsers install chrome
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer